# Generated by Django 5.2.11 on 2026-02-28 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Номер на документ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Чернова"),
                            ("RECEIVED", "Получена"),
                            ("CANCELLED", "Отказана"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Обща сума",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Бележки"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Получена на"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="tenants.location",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Единична цена",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Обща цена",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.delivery",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ред от доставка",
                "verbose_name_plural": "Редове от доставка",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("DELIVERY", "Доставка"),
                            ("SALE", "Продажба"),
                            ("VOID", "Сторно"),
                            ("ADJUSTMENT", "Корекция"),
                            ("TRANSFER_IN", "Вътрешен трансфер — вход"),
                            ("TRANSFER_OUT", "Вътрешен трансфер — изход"),
                            ("WASTE", "Брак"),
                            ("RETURN", "Връщане"),
                        ],
                        max_length=20,
                        verbose_name="Тип движение",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Себестойност",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Order UUID, Delivery ID, etc.",
                        max_length=100,
                        verbose_name="Референция",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Бележки"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="tenants.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение на стока",
                "verbose_name_plural": "Движения на стоки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Име")),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Фирма"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="ЕИК / Булстат",
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="ДДС номер"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Лице за контакт",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Адрес"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Бележки"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставчик",
                "verbose_name_plural": "Доставчици",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="inventory.supplier",
            ),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Праг за предупреждение при нисък запас",
                        max_digits=12,
                        verbose_name="Минимално количество",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="tenants.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Наличност",
                "verbose_name_plural": "Наличности",
                "ordering": ["product__name"],
                "unique_together": {("location", "product")},
            },
        ),
    ]
