# Generated by Django 5.2.11 on 2026-03-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("orders", "0002_alter_order_location"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("device__isnull", True)),
                fields=("tenant", "receipt_sequence"),
                name="unique_web_order_sequence_per_tenant",
            ),
        ),
    ]
