# Generated by Django 5.2.11 on 2026-02-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("card_number", models.CharField(max_length=50)),
                ("customer_number", models.IntegerField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("blocked_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("physical_number", models.CharField(max_length=50, unique=True)),
                ("logical_number", models.CharField(max_length=50, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cards",
                        to="tenants.tenantuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("credit_allowed", models.BooleanField(default=False)),
                (
                    "overdraft_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("second_payment_allowed", models.BooleanField(default=False)),
                ("available_from", models.TimeField(blank=True, null=True)),
                ("available_until", models.TimeField(blank=True, null=True)),
                (
                    "auto_top_up_amount_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("auto_top_up_day_1", models.IntegerField(blank=True, null=True)),
                ("auto_top_up_day_2", models.IntegerField(blank=True, null=True)),
                ("auto_top_up_day_3", models.IntegerField(blank=True, null=True)),
                ("auto_top_up_day_4", models.IntegerField(blank=True, null=True)),
                (
                    "auto_top_up_amount_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("top_up_from_zero", models.BooleanField(default=False)),
                ("override_preferred_prices", models.BooleanField(default=False)),
                (
                    "discount_on_open",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("print_balance", models.BooleanField(default=True)),
                ("print_accumulated", models.BooleanField(default=False)),
                ("preferred_price_allowed", models.BooleanField(default=False)),
                ("pay_with_preferred_price", models.BooleanField(default=False)),
                ("pay_with_card_discount", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_groups",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("company_name", models.CharField(blank=True, max_length=100)),
                (
                    "balance_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "accumulated_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "accumulated_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("pin_hash", models.CharField(blank=True, max_length=128)),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="clients.card",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_accounts",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "client_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="clients.clientgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpendingLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "limit_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Дневен"),
                            ("WEEKLY", "Седмичен"),
                            ("MONTHLY", "Месечен"),
                        ],
                        max_length=10,
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.posdevice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spending_limits",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceClientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_mode", models.IntegerField(default=0)),
                (
                    "client_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_links",
                        to="clients.clientgroup",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_group_links",
                        to="tenants.posdevice",
                    ),
                ),
            ],
            options={
                "unique_together": {("device", "client_group")},
            },
        ),
        migrations.CreateModel(
            name="LimitClientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limit_links",
                        to="clients.clientgroup",
                    ),
                ),
                (
                    "limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_links",
                        to="clients.spendinglimit",
                    ),
                ),
            ],
            options={
                "unique_together": {("client_group", "limit")},
            },
        ),
    ]
