# Generated by Django 5.2.11 on 2026-02-28 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Обект София център"),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                ("city", models.CharField(max_length=100, verbose_name="Град")),
                (
                    "object_name",
                    models.CharField(
                        max_length=50, verbose_name="Кратко име за принтера"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Име на фирмата"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("tax_number", models.CharField(max_length=20, verbose_name="ЕИК")),
                (
                    "plan",
                    models.CharField(
                        choices=[("FREE", "Free"), ("BASIC", "Basic"), ("PRO", "Pro")],
                        default="FREE",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="POSDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logical_name",
                    models.CharField(max_length=50, verbose_name="КАСА_1"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Каса 1 - Зала"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "api_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="tenants.location",
                    ),
                ),
            ],
            options={
                "ordering": ["logical_name"],
            },
        ),
        migrations.AddField(
            model_name="location",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="tenants.tenant",
            ),
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Собственик"),
                            ("MANAGER", "Мениджър"),
                            ("CASHIER", "Касиер"),
                            ("ACCOUNTANT", "Счетоводител"),
                            ("AUDITOR", "Одитор"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Карта за идентификация"
                    ),
                ),
                (
                    "pin_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="PIN за вход на каса"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff",
                        to="tenants.location",
                        verbose_name="Достъп до обекти",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenantuser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name"],
            },
        ),
    ]
